2025-03-04 10:27:53,442 INFO    MainThread:78654 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_setup.py:_flush():67] Configure stats pid to 78654
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_setup.py:_flush():67] Loading settings from /home/w2sg-arnav/.config/wandb/settings
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_setup.py:_flush():67] Loading settings from /home/w2sg-arnav/cotton-disease/notebooks/wandb/settings
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/offline-run-20250304_102753-5s171kbr/logs/debug.log
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/offline-run-20250304_102753-5s171kbr/logs/debug-internal.log
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x79c1a7970970>
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_init.py:init():761] calling init triggers
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-04 10:27:53,443 INFO    MainThread:78654 [wandb_init.py:init():784] starting backend
2025-03-04 10:27:53,676 INFO    MainThread:78654 [wandb_init.py:init():788] sending inform_init request
2025-03-04 10:27:53,682 INFO    MainThread:78654 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-04 10:27:53,683 INFO    MainThread:78654 [wandb_init.py:init():803] backend started and connected
2025-03-04 10:27:53,702 INFO    MainThread:78654 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-04 10:27:53,703 INFO    MainThread:78654 [wandb_init.py:init():896] updated telemetry
2025-03-04 10:27:53,737 INFO    MainThread:78654 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 10:27:53,814 INFO    MainThread:78654 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 10:27:53,947 INFO    MainThread:78654 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 10:27:53,947 INFO    MainThread:78654 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 10:27:53,947 INFO    MainThread:78654 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 10:27:53,947 INFO    MainThread:78654 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 10:27:53,948 INFO    MainThread:78654 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 10:27:58,002 WARNING MsgRouterThr:78654 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-04 10:27:58,003 INFO    MsgRouterThr:78654 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
2025-03-04 10:27:58,173 INFO    MainThread:78654 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-04 10:27:58,173 INFO    MainThread:78654 [wandb_init.py:_pause_backend():564] pausing backend
